services:
  qa-bash:
    image: sinfallas/base-bash-qa:latest
    container_name: bash_test_env
    hostname: bash_qa
    pull_policy: always
    environment:
      TZ: 'America/Caracas'
    volumes:
      - .:/app
    # Mantiene el entorno vivo para recibir comandos efímeros
    command: bash -c "echo 'Contenedor QA Bash listo. Usa docker compose run --rm qa-bash [comando]'; sleep infinity"
