services:
  qa-bash:
    image: sinfallas/base-bash-qa:latest
    container_name: bash_test_env
    hostname: bash_test_env
    pull_policy: always
    environment:
      TZ: 'America/Caracas'
    volumes:
      - .:/app
    command: bash -c "echo 'Contenedor QA Bash listo. Usa docker compose run --rm qa-bash [comando]'; sleep infinity"

  pushgateway:
    image: prom/pushgateway:latest
    container_name: bash_pushgateway
    hostname: bash_pushgateway
    profiles:
      - observability
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:latest
    container_name: bash_prometheus
    hostname: bash_prometheus
    profiles:
      - observability
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "
        global:
          scrape_interval: 2s
        scrape_configs:
          - job_name: 'bash_pushgateway'
            static_configs:
              - targets: ['pushgateway:9091']
        " > /tmp/prometheus.yml
        /bin/prometheus --config.file=/tmp/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - pushgateway
