services:
  # 1. LA APLICACIÓN REAL (Debe estar corriendo en segundo plano para Karate, Locust y Schemathesis)
  api:
    image: sinfallas/base-python-uv:3.13
    container_name: fastapi_api
    hostname: api
    pull_policy: always
    environment:
      TZ: 'America/Caracas'
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    command: bash -c "uv pip install --system -e '.[dev]' && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  # 2. Entorno Python para pytest, tox, schemathesis y locust
  test:
    image: sinfallas/base-python-uv:3.13
    container_name: fastapi_test
    hostname: test_env
    pull_policy: always
    environment:
      TZ: 'America/Caracas'
      UV_PYTHON_DOWNLOADS: 'true'
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "echo 'Contenedor Python listo. Usa docker compose run --rm test [comando]'; sleep infinity"

  # 3. Entorno BDD (Java/Maven) para pruebas de caja negra
  karatelabs:
    image: sinfallas/karatelabs:latest
    container_name: fastapi_karate
    pull_policy: always
    depends_on:
      - api
    volumes:
      - ./test:/app/src/test/java/examples/test
    command: bash -c "echo 'Contenedor Karate listo. Usa docker compose run --rm karatelabs mvn clean test'; sleep infinity"
